<?php

/*************************************************************
        DRUPAL HOOKS
*************************************************************/

/**
 * Implementation of hook_node_load();
 */
function pathauto_export_node_load($nodes, $types) {
  // manually load the node path on features pages so that it gets exported along
  // with the rest of the content
  if (!empty($nodes) && preg_match('#^admin/structure/features/.+#i', $_GET['q'])) {
    module_load_include('inc', 'pathauto');
  
    foreach ($nodes as $node) {
      if ($pathauto_alias = pathauto_create_alias('node', 'return', 'node/' . $node->nid, array('node' => $node), $node->type, $node->language)) {
        $node->path = array(
          'source'  => 'node/' . $node->nid,
          'alias'   => $pathauto_alias,
        );
      }
    }
  }
}

/*************************************************************
        MODULE HOOKS
*************************************************************/

/*************************************************************
        CALLBACKS
*************************************************************/

/*************************************************************
        FORMS
*************************************************************/

/*************************************************************
        THEMING
*************************************************************/

/*************************************************************
        HELPERS / API
*************************************************************/

/*************************************************************
        INTERNAL
*************************************************************/






