<?php

/**
 * @file
 * Contains configuration settings.
 */

define('GS_HELPER_PATH', drupal_get_path('module', 'gs_helper'));

define('GS_TID_BLOGS',                610);
define('GS_TID_BLOGS_ARTS',           618);
define('GS_TID_BLOGS_BOOKS',          617);
define('GS_TID_BLOGS_FOOD',           622);
define('GS_TID_BLOGS_LGBT',           632);
define('GS_TID_BLOGS_LIFE',           624);
define('GS_TID_BLOGS_MOVIES',         615);
define('GS_TID_BLOGS_MUSIC',          611);
define('GS_TID_BLOGS_NEWS',           625);
define('GS_TID_BLOGS_STYLE',          626);
define('GS_TID_BLOGS_TECH',           616);

// menu items
define('GS_TID_NEWS',                 433);
define('GS_TID_NEWS_COMMENTARY',      497);
define('GS_TID_NEWS_SPORTS',          595);
define('GS_TID_NEWS_EVENT_LISTINGS',   -1);

define('GS_TID_MUSIC',                430);
define('GS_TID_MUSIC_REVIEWS',        471);
define('GS_TID_MUSIC_CLUB_LISTINGS',   -1);
define('GS_TID_MUSIC_MUSIC_LISTINGS',  -1);

define('GS_TID_ARTS',                 429);
define('GS_TID_ARTS_REVIEWS',         659);
define('GS_TID_ARTS_LISTINGS',         -1);

define('GS_TID_MOVIES',               439);
define('GS_TID_MOVIES_REVIEWS',       542);
define('GS_TID_MOVIES_LISTINGS',       -1);

define('GS_TID_FOOD',                 437);
define('GS_TID_FOOD_GOLDEN_PLATES',   658);
define('GS_TID_FOOD_LISTINGS',         -1);

define('GS_TID_CLASSIFIEDS',           -1);

define('GS_TID_LIFE',                 449);
define('GS_TID_LIFE_SAVAGE_LOVE',     660);
define('GS_TID_LIFE_ASTROLOGY',       593);
define('GS_TID_LIFE_CARTOONS',        588);
define('GS_TID_LIFE_BOOKS',           438);
define('GS_TID_LIFE_STYLE',           431);
define('GS_TID_LIFE_DRIVING',         592);
define('GS_TID_LIFE_HEALTH',          587);
define('GS_TID_LIFE_TRAVEL',          585);
define('GS_TID_LIFE_LGBT',            600);
define('GS_TID_LIFE_MINDBODYSOUL',    590);
define('GS_TID_LIFE_PHOTO_GALLERIES',  -1);
define('GS_TID_LIFE_TECH_GAMES',      434);

// other required items
define('GS_TID_ARTS_NOTES',           459);