<?php

/*************************************************************
                DRUPAL HOOKS
*************************************************************/

/**
 * Implementation of hook_init();
 */
function gs_profile_init() {
  drupal_add_js(drupal_get_path('module', 'gs_profile') . '/js/gs_profile_on.js');// Allow admin menu on ALL PAGES change of August 1st 2012
  /*if (arg(0) == 'user') {
    drupal_add_js(drupal_get_path('module', 'gs_profile') . '/js/gs_profile_on.js');
  }
  else {
    drupal_add_css(drupal_get_path('module', 'gs_profile') . '/css/gs_profile.css');
    drupal_add_js(drupal_get_path('module', 'gs_profile') . '/js/gs_profile_off.js');
  }*/
}

/**
 * Implementation of hook_menu();
 */
function gs_profile_menu() {
  $items['user/%user/notification'] = array(
    'title' => t('Notifications'),
    'page callback' => 'gs_profile_notification',
    'page arguments' => array(1),
    'access callback' => 'gs_profile_notification_access',
    'type' => MENU_LOCAL_TASK,
    );
  $items['user/%user/delete'] = array(
    'title' => t('Delete account'),
    'page callback' => 'gs_profile_delete',
    'page arguments' => array(1),
    'access callback' => 'gs_profile_delete_access',
    'type' => MENU_LOCAL_TASK,
    );
    
  return $items;
}

/**
 * Access callback for user/%user/notification 
 */
function gs_profile_notification_access() {
  global $user;
  if (arg(0) == 'user' && is_numeric(arg(1))) {
    if ($user->uid == arg(1) || isset($user->roles[3]) || isset($user->roles[4])) {// Allow admin and editors
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Access callback for user/%user/delete
 */
function gs_profile_delete_access() {
  global $user;
  if (arg(0) == 'user' && is_numeric(arg(1))) {
    if ($user->uid == arg(1) || isset($user->roles[3])) {// Allow admin only
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Page callback for menu item user/%user/delete
 */
function gs_profile_delete() {
  return drupal_get_form('gs_profile_delete_form');
}

/**
 * Page callback for menu item user/%user/notification
 */
function gs_profile_notification($account) {

  return drupal_get_form('gs_profile_nofications_form');
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function gs_profile_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
  global $user;
  // adding cancel button
  $form['actions']['submit']['#value'] = 'SAVE CHANGES';
  $form['actions']['submit']['#weight'] = 1;
  $form['actions']['cancel_action']['#value'] = 'CANCEL';
  $form['actions']['cancel_action']['#type'] = 'submit';
  $form['actions']['cancel_action']['#weight'] = 0;
  $form['actions']['cancel_action']['#submit'] = array(0 => 'gs_profile_cancel_action');

  if (arg(0) == 'user' && is_numeric(arg(1)) && arg(2) == 'edit' && arg(3) == 'profile') {
    $form['#prefix'] = '<h2>Profile Information</h2>';
  }
  elseif (arg(0) == 'user' && is_numeric(arg(1)) && arg(2) == 'edit') {
    $form['account']['mail']['#prefix'] = '<div class="email-user-profile"><h2>Email address</h2>Your current email address is displayed below. To update, enter a new email address and confirm the change by entering your password at the bottom of the page.';
    $form['account']['mail']['#suffix'] = '</div>';
    $form['account']['mail']['#title'] = 'EMAIL ADDRESS';
    $form['account']['mail']['#size'] = 34;
    $form['account']['pass']['#prefix'] = '<div class="password-user-profile"><h2>Change Password</h2>To update your password, enter and confirm a new password in the fields below. Then confirm this change by entering your old password at the bottom of the page.';
    $form['account']['pass']['#suffix'] = '</div><div class="close-account-user-profile"><h2>Close Account</h2><div class="description">Please read carefully - this action cannot be undone. Your profile information will be erased and you will no longer be able to sign in to this account: <a href="/user/' . arg(1) . '/delete" class="close-my-account">CLOSE MY ACCOUNT</a></div></div>';
    unset($form['account']['pass']['#description']);
    // $form['account']['pass']['#title'] = 'NEW PASSWORD';
    $form['account']['current_pass']['#title'] = '<h2>Confirm Changes</h2>PASSWORD';
    $form['account']['current_pass']['#description'] = '';
    $form['account']['current_pass']['#size'] = 34;
    $form['account']['current_pass']['#weight'] = 10;
  }
  
  if (isset($user->roles[2]) && !isset($user->roles[3]) && !isset($user->roles[4])){
    unset($form['redirect']);
    unset($form['#metatags']);
    unset($form['contact']);
  }
}

function gs_profile_cancel_action() {
  drupal_goto(current_path());
}

/**
 * Implements hook_admin_paths_alter().
 */
function gs_profile_admin_paths_alter(&$paths) {
  // Treat all user pages as administrative.
  $paths['user/*/edit'] = FALSE;
  $paths['user/*/edit/profile'] = FALSE;
}

/**
 * Implements hook_menu_local_tasks_alter(
 */
function gs_profile_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  global $user;
  if(arg(0) == 'user' && $user->uid > 0) {
    $account = array(); $profile = array(); $notification = array(); $view = array();
    foreach($data['tabs'][0]['output'] as $key => $value) {
      if ($value['#link']['path'] == 'user/%/edit') {
        $value['#link']['title'] = 'Account';
        $account = $value;
      }
      if ($value['#link']['path'] == 'user/%/notification') {
        $notification = $value;
      }
      if ($value['#link']['path'] == 'user/%/view') {
        $view = $value;
      }
      if($user->uid > 1) {
        unset($data['tabs'][0]['output'][$key]);
      }
    }
    if (arg(0) == 'user' && is_numeric(arg(1))) {
      $all = array(
        'path' => 'user/%/edit/profile',
        'load_functions' => array( 1 => 'user_category_load' ),
        'access_callback' => 'user_edit_access',
        'page_callback' => 'drupal_get_form',
        'tab_parent' => 'user/%/edit',
        'tab_root' => 'user/%',
        'title' => 'Profile',
        'title_callback' => 'check_plain',
        'weight' => 3,
        'include_file' => 'modules/user/user.pages.inc',
        'href' => 'user/' . arg(1) . '/edit/profile',
        'tab_root_href' => 'user/' . arg(1),
        'tab_parent_href' => 'user/' . arg(1) . '/edit',
        'access' => 1,
        'localized_options' => array( 'html' => 1 ),
      );
      $profile = array(
        '#theme' => 'menu_local_task',
        '#link' => $all,
      );
      if (arg(0) == 'user' && is_numeric(arg(1)) && arg(2) == 'edit' && arg(3) == 'profile') {
        $profile['#active'] = TRUE;
      }
    }
    if($user->uid > 1) {
      $data['tabs'][0]['output'] = array($view, $account, $profile, $notification);
      $data['tabs'][0]['count'] = 3;
      unset($data['tabs'][1]);
    }
  }
}

/*************************************************************
                FORMS
*************************************************************/

/**
 * Implementation of delete form on page: user/%user/delete
 */
function gs_profile_delete_form() {
  
  $form['type'] = array(
    '#type' => 'value', 
    '#value' => "delete",
  );
  $form['actions'] = array(
    '#type' => 'actions',
    'Agree' => array(
      '#type' => 'submit',
      '#value' => 'Delete account',
      '#prefix' => '<h2>Are you sure you want to delete your account? This cannot be undone.</h2>',
    ),
    'Disagree' => array(
      '#type' => 'submit',
      '#value' => 'Cancel',
    ),
  );

  return $form;
}

/**
 * Submit handler for form gs_profile_delete
 */
function gs_profile_delete_form_submit($form, &$form_state) {
  if($form_state['clicked_button']['#value'] == "Delete account"){
    global $user;
    if ($user->uid != arg(1) || arg(1) == 1) { // double checking, better safe than sorry
      drupal_goto("user");
    }
    $user->status = 0;
    $original = clone $user;
    $user->original = $original;
    user_save($user);
    watchdog("gs_profile", "User " . $user->uid . " has deactivated his/her account", $variables = array(), $severity = WATCHDOG_NOTICE);
  }
  else {
    drupal_goto("user");
  }
}

/**
 * Implementation of notification form on page: user/%user/notification
 */
function gs_profile_nofications_form($form_state) {
  
  $account = user_load(arg(1));

  $default_value_notify = TRUE; $default_value_news_list = TRUE; $default_value_list_list = FALSE;
  $dbresult = db_query("SELECT * FROM {profile} WHERE uid = :n LIMIT 0, 1", array(':n' => $account->uid));

  foreach ($dbresult as $record) {
    $notify_dbresult = db_query("SELECT * FROM {field_data_field_notify} WHERE entity_id = :n LIMIT 0, 1", array(':n' => $record->pid));
    foreach ($notify_dbresult as $notify_record) {
      $default_value_notify = $notify_record->field_notify_value;
    }
  }
  
  module_load_include('inc', 'gs_profile', 'inc/gs_profile_icontact.config');
  $icontact = array(
    'account_id' => GS_PROFILE_ACCOUNT_ID,
    'key' => GS_PROFILE_KEY,
    'user_icontact' => GS_PROFILE_USER,
    'pass' => GS_PROFILE_PASSWORD,
    'client_folder_id' => GS_PROFILE_CLIENT_FOLDER_ID,
  );
  $news_list_id = GS_PROFILE_NEWS_LIST_ID;
  $list_list_id = GS_PROFILE_LIST_LIST_ID;
  $result_str = '';
  $email = $account->mail;
  $firstname = "";
  $lastname = "";
  
  //fetching profile information
  $profile_dbresult = db_query("SELECT * FROM {profile} WHERE uid = :n ORDER BY `changed` DESC LIMIT 0, 1 ", array(':n' => $account->uid));
  foreach ($profile_dbresult as $value) {
    $p2en = entity_load("profile2", array($value->pid));
    if(isset($p2en[$value->pid]->field_first_name['und'][0]['value'])) {
      $firstname = $p2en[$value->pid]->field_first_name['und'][0]['value'];
    }
    if(isset($p2en[$value->pid]->field_last_name['und'][0]['value'])) {
      $lastname = $p2en[$value->pid]->field_last_name['und'][0]['value'];
    }
  }

  $contact_id = gs_profile_icontact_get_contact_id($icontact, $email);
  $news_default_value = gs_profile_icontact_get_subscription($icontact, $news_list_id, $contact_id);
  $list_default_value = gs_profile_icontact_get_subscription($icontact, $list_list_id, $contact_id);
  $form['account']['notify'] = array(
    '#type' => 'checkbox',
    '#prefix' => '<h2>Contact Preferences</h2>',
    '#title' => t('Do not notify me by email of replies to my comments'),
    '#default_value' => $default_value_notify,
  );
  $form['account']['news_list'] = array(
    '#type' => 'checkbox',
    '#title' => t('Sign me up for The News weekly newsletter for headlines from the world of news and entertainment'),
    '#default_value' => $news_default_value,
  );
  $form['account']['list_list'] = array(
    '#type' => 'checkbox',
    '#title' => t('Sign me up for The List newsletter to enter contests to win movie passes, DVDs, books, trips and more. List members also get advance notice of concert tickets prebuys.'),
    '#default_value' => $list_default_value,
  );
  $form['actions']['#prefix'] = '<div class="actions-notification-form">';
  $form['account']['hidden_news'] = array('#type' => 'hidden', '#value' => $news_default_value);
  $form['account']['hidden_list'] = array('#type' => 'hidden', '#value' => $list_default_value);
  $form['actions']['cancel'] = array('#type' => 'submit', '#value' => t('CANCEL'), '#submit' => array(0 => 'gs_profile_cancel_action'), '#weight' => 10);
  $form['actions']['submit'] = array('#type' => 'submit', '#value' => t('SAVE CHANGES'), '#weight' => 11);
  $form['actions']['#suffix'] = '</div>';
  
  // Link to edit profile on icontact
  // http://app.icontact.com/icp/mmail-mprofile.pl?r=60629731&l=34283&s=GYGD&m=459937&c=463136
  
  return $form;

}

/**
 * Submit handler for form gs_profile_nofications
 */
function gs_profile_nofications_form_submit($form, &$form_state) {
  $account = user_load(arg(1));

  module_load_include('inc', 'gs_profile', 'inc/gs_profile_icontact.config');
  $icontact = array(
    'account_id' => GS_PROFILE_ACCOUNT_ID,
    'key' => GS_PROFILE_KEY,
    'user_icontact' => GS_PROFILE_USER,
    'pass' => GS_PROFILE_PASSWORD,
    'client_folder_id' => GS_PROFILE_CLIENT_FOLDER_ID,
  );
  $news_list_id = GS_PROFILE_NEWS_LIST_ID;
  $list_list_id = GS_PROFILE_LIST_LIST_ID;

  $account_info = array('firstname' => '', 'lastname' => '', 'postal_code' => '', 'age' => '', 'sex' => '', 'email' => $account->mail);

  //fetching profile information
  $profile_dbresult = db_query("SELECT * FROM {profile} WHERE uid = :n ORDER BY `changed` DESC LIMIT 0, 1 ", array(':n' => $account->uid));
  foreach ($profile_dbresult as $value) {
    $p2en = entity_load("profile2", array($value->pid));
    if(isset($p2en[$value->pid]->field_first_name['und'][0]['value'])) { $account_info['firstname'] = $p2en[$value->pid]->field_first_name['und'][0]['value'];}
    if(isset($p2en[$value->pid]->field_last_name['und'][0]['value'])) { $account_info['lastname'] = $p2en[$value->pid]->field_last_name['und'][0]['value'];}
    if(isset($p2en[$value->pid]->field_postcode['und'][0]['value'])) { $account_info['postal_code'] = $p2en[$value->pid]->field_postcode['und'][0]['value'];}
    if(isset($p2en[$value->pid]->field_age['und'][0]['value'])) { $account_info['age'] = $p2en[$value->pid]->field_age['und'][0]['value'];}
    if(isset($p2en[$value->pid]->field_gender['und'][0]['value'])) { $account_info['sex'] = $p2en[$value->pid]->field_gender['und'][0]['value'];}
  }

  // News newsletter
  if($form_state['input']['news_list'] != $form_state['input']['hidden_news']) {
    if ($form_state['input']['news_list'] == 1) {
      
      gs_profile_icontact_add_contact($icontact, $account_info['email'], $account_info['firstname'], $account_info['lastname']); 
      $account_info['pid'] = gs_profile_icontact_get_contact_id($icontact, $account_info['email']);
      if (gs_profile_icontact_set_subscription($icontact, $news_list_id, $account_info['pid']) == 0) {
        gs_profile_subscribe_user_with_email($account_info, $icontact, $news_list_id, 'News');
      }
      else {
        drupal_set_message("You have been subscribed to the News newsletter.");
      }
    }
    else {
      if(gs_profile_icontact_unsubscribe($icontact, $news_list_id, gs_profile_icontact_get_contact_id($icontact, $account_info['email'])) == 1) {
        drupal_set_message("You have been unsubscribed from the News newsletter.");
      }
    }
  }

  // List newsletter
  if($form_state['input']['list_list'] != $form_state['input']['hidden_list']) {
    if ($form_state['input']['list_list'] == 1) {

      gs_profile_icontact_add_contact($icontact, $account_info['email'], $account_info['firstname'], $account_info['lastname']); 
      $account_info['pid'] = gs_profile_icontact_get_contact_id($icontact, $account_info['email']);
      
      if (gs_profile_icontact_set_subscription($icontact, $list_list_id, $account_info['pid']) == 0) {
        gs_profile_subscribe_user_with_email($account_info, $icontact, $list_list_id, 'List');
      }
      else {
        drupal_set_message("You have been subscribed to the List newsletter.");
      }
    }
    else {
      if(gs_profile_icontact_unsubscribe($icontact, $list_list_id, gs_profile_icontact_get_contact_id($icontact, $account_info['email'])) == 1) {
        drupal_set_message("You have been unsubscribed from the List newsletter.");
      }
    }
  }

  // notify by email
  $notify = $form_state['input']['notify'];
  $dbresult = db_query("SELECT * FROM {profile} WHERE uid = :n LIMIT 0, 1", array(':n' => $account->uid));
  
  foreach ($dbresult as $record) {
    $notify_dbresult = db_query("SELECT * FROM {field_data_field_notify} WHERE entity_id = :n LIMIT 0, 1", array(':n' => $record->pid));
    
    foreach ($notify_dbresult as $notify_record) {
      $sql = "UPDATE {field_revision_field_notify} SET field_notify_value = :n WHERE entity_type = :ent AND deleted = :del AND entity_id = :eni AND revision_id = :rev AND language = 'und' AND delta = :del;";
      $dbresult = db_query($sql, array(':n' => $notify, ':ent' => $notify_record->entity_type, ':del' => $notify_record->deleted, ':eni' => $notify_record->entity_id, ':rev' => $notify_record->revision_id, ':del' => $notify_record->delta));
      $sql = "UPDATE {field_data_field_notify} SET field_notify_value = :n WHERE entity_type = :ent AND deleted = :del AND entity_id = :eni AND revision_id = :rev AND language = 'und' AND delta = :del;";
      $dbresult = db_query($sql, array(':n' => $notify, ':ent' => $notify_record->entity_type, ':del' => $notify_record->deleted, ':eni' => $notify_record->entity_id, ':rev' => $notify_record->revision_id, ':del' => $notify_record->delta));
    }
  }
}

/**
 * Subscribe user via email 
 */
function gs_profile_subscribe_user_with_email($account_info, $icontact, $list_id, $list_name) {
  $to = 'm_keir@straight.com'; // email of our newsletter administrator

  $site_email = variable_get('site_mail', '');
  $my_module = 'gs_profile';
  $my_mail_token = time();
  $from = variable_get('system_mail', $site_email);
  $message = array(
      'id' => $my_module . '_' . $my_mail_token,
      'to' => $to,
      'subject' => 'Add Subscriber ' . $account_info['email'] . ' to newsletter News',
      'body' => '
User Email: ' . $account_info['email'] . ' 
First Name: ' . $account_info['firstname'] . '
Last Name: ' . $account_info['lastname'] . ' 
Postal Code: ' . $account_info['postal_code'] . ' 
Age: ' . $account_info['age'] . ' 
Sex: ' . $account_info['sex'] . ' 
User IContact ID: ' . $account_info['pid'] . ' 

Listname: ' . $list_name . '
ListId: ' . $list_id . '
https://www.icontact.com/login',
      'headers' => array(
      'From' => $from, 
      'Sender' => $from, 
      'Return-Path' => $from,
    ),
  );
  $system = drupal_mail_system('gs_profile', $my_mail_token);
  if ($system->mail($message)) {
    drupal_set_message('Your request to subscribe to the ' . $list_name. ' newsletter has been sent to our site administrator, you will be subscribed soon.');
  }
  else {
    drupal_set_message("Email failure, please try again later.", "warning");
  }
}
/*************************************************************
                ICONTACT HELPER FUNCTIONS
*************************************************************/

/**
 * Returns client folder id
 * This function is used for the setup, as client_folder_id doesn't change we store the variable in gs_profile_icontact_config.inc 
 */
function gs_profile_icontact_login($icontact, $pass) 
{ 
  // Build iContact authentication 
  $headers = array( 
    'Accept: text/xml', 
    'Content-Type: text/xml', 
    'Api-Version: 2.0', 
    'Api-AppId: ' . $icontact['key'], 
    'Api-Username: ' . $icontact['user_icontact'], 
    'Api-Password: ' . $icontact['pass'] 
  ); 

  // Connect to iContact to retrieve the client folder id 
  $ch=curl_init("https://app.icontact.com/icp/a/$account_id/c/"); 
  curl_setopt($ch, CURLOPT_HTTPHEADER, $headers); 
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); 
  curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false); 
  $buf = curl_exec($ch); 
  curl_close($ch); 

  // Extract client folder id from response 
  $client_folder_id = ""; 
  if (($pos=strpos($buf,"<clientFolderId>"))!==false) 
  { 
    $client_folder_id = substr($buf, strlen("<clientFolderId>")+$pos); 
    if (($pos=strpos($client_folder_id,"<"))!==false) 
    { 
      $client_folder_id = substr($client_folder_id, 0, $pos); 
    } 
  } 

  // Return client folder id
  return $client_folder_id; 
} 

/**
 * Subscribe user with $contact_id to list $lsit_id
 */
function gs_profile_icontact_set_subscription($icontact, $list_id, $contact_id) 
{ 
  // Build iContact authentication 
  $headers = array( 
    'Accept: text/xml', 
    'Content-Type: text/xml', 
    'Api-Version: 2.0', 
    'Api-AppId: ' . $icontact['key'], 
    'Api-Username: ' . $icontact['user_icontact'], 
    'Api-Password: ' . $icontact['pass'] 
  ); 

  // Build subscription record 
  $data = '<?xml version="1.0" encoding="UTF-8"?>'."\r\n<subscriptions>\r\n"; 
  $data.= "<subscription>\r\n"; 
  $data.= "<contactId>$contact_id</contactId>\r\n"; 
  $data.= "<listId>$list_id</listId>\r\n"; 
  $data.= "<status>normal</status>\r\n"; 
  $data.= "</subscription>\r\n</subscriptions>"; 

  // Add subscription 
  $ch=curl_init("https://app.icontact.com/icp/a/".$icontact['account_id']."/c/".$icontact['client_folder_id']."/subscriptions/");
  curl_setopt($ch, CURLOPT_HTTPHEADER, $headers); 
  curl_setopt($ch, CURLOPT_POSTFIELDS, $data); 
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); 
  curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false); 
  $buf = curl_exec($ch); 
  curl_close($ch); 

  // Extract subscriptionID from response 
  $subscription_id = 0; 
  if (($pos=strpos($buf,"<subscriptionId>"))!==false) 
  { 
    $subscription_id = substr($buf, $pos+strlen("<subscriptionId>")); 
    if (($pos=strpos($subscription_id,"<"))!==false) 
    { 
      $subscription_id = substr($subscription_id,0,$pos); 
    } 
  } 

  // If the subscription could not be updated return 0
  if(strpos($buf,"could not be updated") > 0) {
    $subscription_id = 0;
  }

  // Return result 
  return $subscription_id; 
} 

/**
 * Add user with $email to the GS account on IContact (this does not subscribe the user to any list)
 */
function gs_profile_icontact_add_contact($icontact, $email, $firstname, $lastname) 
{ 
  // Build iContact authentication 
  $headers = array( 
    'Accept: text/xml', 
    'Content-Type: text/xml', 
    'Api-Version: 2.0', 
    'Api-AppId: ' . $icontact['key'], 
    'Api-Username: ' . $icontact['user_icontact'], 
    'Api-Password: ' . $icontact['pass'] 
  ); 
          
  // Build contact record 
  $data = '<?xml version="1.0" encoding="UTF-8"?>'."\r\n<contacts>\r\n"; 
  $data.= "<contact>\r\n"; 
  $data.= "<email>$email</email>\r\n"; 
  $data.= "<firstName>$firstname</firstName>\r\n"; 
  $data.= "<lastName>$lastname</lastName>\r\n"; 
  $data.= "<status>normal</status>\r\n"; 
  $data.= "</contact>\r\n</contacts>"; 

  // Add contact 
  $ch=curl_init("https://app.icontact.com/icp/a/".$icontact['account_id']."/c/".$icontact['client_folder_id']."/contacts/");
  curl_setopt($ch, CURLOPT_HTTPHEADER, $headers); 
  curl_setopt($ch, CURLOPT_POSTFIELDS, $data); 
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); 
  curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false); 
  $buf = curl_exec($ch); 
  curl_close($ch); 

  // Extract contactId from response 
  $contact_id = ""; 
  if (($pos=strpos($buf,"<contactId>"))!==false) 
  { 
    $contact_id = substr($buf, $pos+strlen("<contactId>")); 
    if (($pos=strpos($contact_id,"<"))!==false) 
    { 
      $contact_id = substr($contact_id,0,$pos); 
    } 
  } 

  // If we have a contact id, we're good 
  $result = !empty($contact_id); 

  // Return result 
  return $result; 
} 

/**
 * Return contactid of user with $email
 */
function gs_profile_icontact_get_contact_id($icontact, $email) 
{ 
  // Build iContact authentication 
  $headers = array( 
    'Accept: text/xml', 
    'Content-Type: text/xml', 
    'Api-Version: 2.0', 
    'Api-AppId: ' . $icontact['key'], 
    'Api-Username: ' . $icontact['user_icontact'], 
    'Api-Password: ' . $icontact['pass'] 
  ); 
          
  // GET contact 
  $ch=curl_init("https://app.icontact.com/icp/a/".$icontact['account_id']."/c/".$icontact['client_folder_id']."/contacts?email=".URLEncode($email)); 
  curl_setopt($ch, CURLOPT_HTTPHEADER, $headers); 
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); 
  curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false); 
  $buf = curl_exec($ch); 
  curl_close($ch); 

  // Extract contact id from response 
  $contact_id = 0;
  if (($pos=strpos($buf,"<contactId>"))!==false) 
  {
    $contact_id = substr($buf, $pos+strlen("<contactId>")); 
    if (($pos=strpos($contact_id,"<"))!==false) 
    {
      $contact_id = substr($contact_id,0,$pos); 
    }
  }

  // Return contact id
  return $contact_id; 
} 

/**
 * Return subscription id for user with $contact_id on list with $list_id
 */
function gs_profile_icontact_get_subscription($icontact, $list_id, $contact_id) 
{ 
  // Build iContact authentication 
  $headers = array( 
    'Accept: text/xml', 
    'Content-Type: text/xml', 
    'Api-Version: 2.0', 
    'Api-AppId: ' . $icontact['key'], 
    'Api-Username: ' . $icontact['user_icontact'], 
    'Api-Password: ' . $icontact['pass'] 
  ); 
          
  // GET contact 
  $ch=curl_init("https://app.icontact.com/icp/a/".$icontact['account_id']."/c/".$icontact['client_folder_id']."/subscriptions/".$list_id."_".$contact_id);
  curl_setopt($ch, CURLOPT_HTTPHEADER, $headers); 
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); 
  curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false); 
  $buf = curl_exec($ch); 
  curl_close($ch); 

  // Extract subscrition status  from response 
  $subscription_state = "";
  if (($pos=strpos($buf,"<status>"))!==false) 
  {
    $subscription_state = substr($buf, $pos+strlen("<status>")); 
    if (($pos=strpos($subscription_state,"<"))!==false) 
    {
      $subscription_state = substr($subscription_state,0,$pos); 
    }
  }

  // return subscription status  
  if($subscription_state == 'normal') {
    return TRUE;
  }
  else {
    return FALSE;
  }
} 

/**
 * Unsubscribe user $contact_id from $list_id
 */
function gs_profile_icontact_unsubscribe($icontact, $list_id, $contact_id) 
{ 
  // Build iContact authentication 
  $headers = array( 
    'Accept: text/xml', 
    'Content-Type: text/xml', 
    'Api-Version: 2.0', 
    'Api-AppId: ' . $icontact['key'], 
    'Api-Username: ' . $icontact['user_icontact'], 
    'Api-Password: ' . $icontact['pass'] 
  ); 

  // Build subscription record 
  $data = '<?xml version="1.0" encoding="UTF-8"?>'."\r\n<subscriptions>\r\n"; 
  $data.= "<subscription>\r\n"; 
  $data.= "<contactId>$contact_id</contactId>\r\n"; 
  $data.= "<listId>$list_id</listId>\r\n"; 
  $data.= "<status>unsubscribed</status>\r\n"; 
  $data.= "</subscription>\r\n</subscriptions>"; 

  // Add subscription 
  $ch=curl_init("https://app.icontact.com/icp/a/".$icontact['account_id']."/c/".$icontact['client_folder_id']."/subscriptions/");
  curl_setopt($ch, CURLOPT_HTTPHEADER, $headers); 
  curl_setopt($ch, CURLOPT_POSTFIELDS, $data); 
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); 
  curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false); 
  $buf = curl_exec($ch); 
  curl_close($ch); 

  // Extract subscriptionID from response 
  $subscription_id = ""; 
  if (($pos=strpos($buf,"<subscriptionId>"))!==false) 
  { 
    $subscription_id = substr($buf, $pos+strlen("<subscriptionId>")); 
    if (($pos=strpos($subscription_id,"<"))!==false) 
    { 
      $subscription_id = substr($subscription_id,0,$pos); 
    } 
  } 

  // If we have a subscription id OR this subscription already unsubscribed, we're good 
  $result = !empty($subscription_id) || strpos($buf,"could not be updated")!==false; 

  // Return result 
  return $result; 
}

