<?php
define('GS_DEBUG_PATH', drupal_get_path('module', 'gs_debug'));

/*************************************************************
				DRUPAL HOOKS
*************************************************************/

/**
 * Implementation of hook_init();
 */
function gs_debug_init() {
  //add css & javascript
  drupal_add_css(GS_DEBUG_PATH . '/css/gs_debug.css');
  drupal_add_js(GS_DEBUG_PATH . '/js/gs_debug.js');
}

/*************************************************************
        HELPERS
*************************************************************/

/*************************************************************
				HELPERS
*************************************************************/

/**
 * Checks to see whether the current user is allowed to see debugging information;
 * @return - boolean
 */
function is_debug() {
  $allowed_ips = array(
    '127.0.0.1',
    '::1',
  );

  global $user;
  
  return (in_array($_SERVER['REMOTE_ADDR'], $allowed_ips) || $user->uid == 1);
}

/**
 * Displays or returns formatted print_r() output;
 * @return - string
 * @param object $data - object to be ran through print_r();
 * @param object $return[optional] - boolean; FALSE to print output, or TRUE to return it;
 */
function print_rr($data, $return = FALSE) {
  if (!is_debug()) {
    return FALSE;
  }
  
  $output = '<pre style="position: relative; z-index: 999999; width: 1000px; text-transform: none; background: #fff; color: #333; padding: 10px; border: 1px #ccc solid; margin: 10px; text-align: left;">';
  $output .= print_r($data, 1);
  $output .= '</pre>';
  
  if ($return) {
   return $output;
  }
  else {
    echo $output;
  }
}

/**
 * Custom drupal_set_message() wrapper;
 * @return 
 * @param object $data
 */
function dsmm($data) {
  drupal_set_message(print_rr($data, 1));
}

