<?php

/**
 * @file
 * Contains configuration settings for IContact.
 */

// Set IContact variables
  
define('GS_PROFILE_ACCOUNT_ID', 463136);
define('GS_PROFILE_KEY', 'aMVb10sOxFtlvZhHk6lqwTLK3e8EG6cl');
define('GS_PROFILE_USER', 'georgiastraight');
define('GS_PROFILE_PASSWORD', '5traight*#');
define('GS_PROFILE_CLIENT_FOLDER_ID', 34283);
define('GS_PROFILE_NEWS_LIST_ID', 47041);
define('GS_PROFILE_LIST_LIST_ID', 45123);
